/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The conditional parts
 */
export type ConditionalPart = {
  variableName: string;
  formulation?: string[];
  comprehension: string[];
  [k: string]: unknown;
}[];

/**
 * Structure of FCG Editor
 */
export interface FCGEditor {
  /**
   * The metadata of the grammar
   */
  base: {
    grammarId: string;
    title: string;
    version?: string;
    description?: string;
    date?: string;
    featureTypes?: {
      argsSequence?: boolean;
      formSetOfPredicates?: boolean;
      meaningSetOfPredicates?: boolean;
      constituentsSequence?: boolean;
      dependentsSequence?: boolean;
      [k: string]: unknown;
    };
    hierarchyFeatures?: {
      constituentsDependents?: boolean;
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  /**
   * Lists of all constructions in the grammar
   */
  constructions: [
    {
      constructionName: string;
      contribution?: ContributionPart;
      conditional: ConditionalPart;
      [k: string]: unknown;
    },
    ...{
      constructionName: string;
      contribution?: ContributionPart;
      conditional: ConditionalPart;
      [k: string]: unknown;
    }[]
  ];
  [k: string]: unknown;
}
/**
 * The contributing parts
 */
export interface ContributionPart {
  units?: {
    variableName: string;
    contents: string[];
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
